// <auto-generated />
namespace EShop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeentrydatepropertyintotheproductclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeentrydatepropertyintotheproductclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201904010521455_remove entrydate property into the product class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
